### PR TITLE
Replace old download scripts

### PR DESCRIPTION
**Pull request by ibaiGorordo**
This pull requests replaces the old download links with the new pattern (sample: https://github.com/PINTO0309/PINTO_model_zoo/commit/db4e3afceb9413b5500b219d78f2ae3840decd4d).

The replacement has been done using the following script: https://gist.github.com/ibaiGorordo/69988fbf83a045e6c58701aa03eb423f

I have not tested the changes, so there might be issues with some of the conversions.

### CODE REVIEW

**Comment by PINTO0309** [comment]
Too wonderful. Other engineers are starting to work on converting the target model, so I will temporarily hold off on this pull request, although I very much appreciate it. However, it appears to be a very effective means of filling in gaps in other engineers' modifications. :100: 

https://github.com/PINTO0309/PINTO_model_zoo/issues
image

**Comment by ibaiGorordo** [comment]
I realized the are mistakes in scripts with two downloads. I need to modify the script to search for the curl line, instead of hard code define the lines.

To avoid the chaos, you can ignore this PR and convert the other models in your local copy.

**Comment by ibaiGorordo** [comment]
I updated the conversion script for multiple downloads and I think the rest are fine, but I might have misses some files with a different pattern.

**Comment by PINTO0309** [comment]
Thanks!

**Comment by PINTO0309** [comment]
@ibaiGorordo Thank you for your time, but can you resolve the conflict? Once the conflict is resolved I would like to merge your proposals in bulk.

**Comment by ibaiGorordo** [comment]
I think it should be fine now. I modified those files manually, but if necessary I think it should be possible to add the rm cookie for the rest of the scripts

**Comment by PINTO0309** [comment]
Thank you! I will reflect the changes once in this state.

**Pull request merged**
